#!/usr/bin/env python3
"""
Mask out **sky** and **car-roof** regions from perspective cubemap images
generated by sparsePointCLoud.py.

Hybrid roof detection (three methods, union)
---------------------------------------------
The GoPro 360 sits on the car roof, so the roof occupies the same pixels
in every frame of a given face direction.  Three complementary methods:

  1. **Depth Anything V2** — The roof is the closest object to the camera,
     so its inverse-depth is very high.  Per-face consensus depth map is
     built by averaging across all frames; an Otsu threshold separates
     the near-field roof from the far-field scene.  Most accurate method.

  2. **SegFormer consensus** — SegFormer (ADE20K, class 20 = car) across
     all frames; pixel = roof if ≥30 % of frames agree.

  3. **Temporal variance** — Roof pixels are static (low std across
     frames).  Connected low-variance region touching the bottom edge.

The final per-face roof mask is the **union** of all three.
Sky detection uses per-image SegFormer (class 2 = sky).

Outputs
-------
  <output_dir>/<image_name>.png
    Binary mask: 0 = masked (sky or roof), 255 = valid region.

Usage
-----
  python maskSkyRoof.py --images_dir output/images --output_dir output/masks
  python maskSkyRoof.py --images_dir output/images --output_dir output/masks --visualize
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

import cv2
import numpy as np
import torch
from PIL import Image
from tqdm import tqdm
from transformers import (
    AutoImageProcessor,
    AutoModelForDepthEstimation,
    SegformerForSemanticSegmentation,
    SegformerImageProcessor,
)


# ADE20K class indices (0-indexed) used by SegFormer
ADE20K_SKY = 2
ADE20K_CAR = 20

# Cubemap face names (must match sparsePointCLoud.py naming convention)
FACE_NAMES = ("front", "right", "back", "left")


# ── Model loading ─────────────────────────────────────────────────────

def load_segformer(device: torch.device):
    """Load SegFormer-B5 fine-tuned on ADE20K."""
    model_name = "nvidia/segformer-b5-finetuned-ade-640-640"
    processor = SegformerImageProcessor.from_pretrained(model_name)
    model = SegformerForSemanticSegmentation.from_pretrained(model_name)
    model.to(device).eval()
    return processor, model


def load_depth_model(device: torch.device):
    """Load Depth Anything V2 Large."""
    model_name = "depth-anything/Depth-Anything-V2-Large-hf"
    processor = AutoImageProcessor.from_pretrained(model_name)
    model = AutoModelForDepthEstimation.from_pretrained(model_name)
    model.to(device).eval()
    return processor, model


# ── Inference helpers ─────────────────────────────────────────────────

@torch.no_grad()
def predict_segmentation(
    image_bgr: np.ndarray,
    processor: SegformerImageProcessor,
    model: SegformerForSemanticSegmentation,
    device: torch.device,
) -> np.ndarray:
    """Run SegFormer and return per-pixel class IDs at original resolution."""
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    inputs = processor(images=image_rgb, return_tensors="pt").to(device)
    logits = model(**inputs).logits

    h, w = image_bgr.shape[:2]
    upsampled = torch.nn.functional.interpolate(
        logits, size=(h, w), mode="bilinear", align_corners=False,
    )
    return upsampled.argmax(dim=1).squeeze(0).cpu().numpy()


@torch.no_grad()
def predict_depth(
    image_bgr: np.ndarray,
    processor: AutoImageProcessor,
    model: AutoModelForDepthEstimation,
    device: torch.device,
) -> np.ndarray:
    """Run Depth Anything V2 and return inverse-depth map (higher = closer)."""
    pil_img = Image.fromarray(cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB))
    inputs = processor(images=pil_img, return_tensors="pt").to(device)
    depth = model(**inputs).predicted_depth  # (1, H', W')

    h, w = image_bgr.shape[:2]
    depth = torch.nn.functional.interpolate(
        depth.unsqueeze(1), size=(h, w), mode="bicubic", align_corners=False,
    ).squeeze().cpu().numpy()
    return depth


# ── Utilities ─────────────────────────────────────────────────────────

def face_name_from_path(img_path: Path) -> str:
    stem = img_path.stem
    for face in FACE_NAMES:
        if stem.endswith(f"_{face}"):
            return face
    return "unknown"


def group_by_face(image_paths: list[Path]) -> dict[str, list[Path]]:
    groups: dict[str, list[Path]] = defaultdict(list)
    for p in image_paths:
        groups[face_name_from_path(p)].append(p)
    return dict(groups)


def _keep_bottom_connected(mask: np.ndarray) -> np.ndarray:
    """Keep only connected components that touch the bottom edge."""
    if not mask.any():
        return mask
    labels_uint8 = mask.astype(np.uint8)
    _, label_map = cv2.connectedComponents(labels_uint8, connectivity=8)
    bottom_labels = set(label_map[-1, :][label_map[-1, :] > 0])
    if not bottom_labels:
        return np.zeros_like(mask)
    out = np.zeros_like(mask)
    for lbl in bottom_labels:
        out |= label_map == lbl
    return out


# Module-level cache for normalised depth maps (used by boundary correction)
_depth_norm_cache: dict[str, np.ndarray] = {}

# ── Method 1: Depth Anything V2 consensus ─────────────────────────────

def build_depth_roof_masks(
    face_groups: dict[str, list[Path]],
    depth_processor: AutoImageProcessor,
    depth_model: AutoModelForDepthEstimation,
    device: torch.device,
    depth_scale: float = 0.7,
    dilate_px: int = 15,
) -> dict[str, np.ndarray]:
    """Build per-face roof mask from consensus inverse-depth.

    Averages inverse-depth across all frames per face, then applies Otsu
    thresholding (scaled by depth_scale) to separate the near-field roof
    from the far-field scene.  A scale < 1.0 lowers the threshold to
    capture more of the roof-to-scene transition zone.
    Only the connected region touching the image bottom is kept.
    """
    roof_masks: dict[str, np.ndarray] = {}

    for face, paths in face_groups.items():
        sample = cv2.imread(str(paths[0]))
        h, w = sample.shape[:2]
        depth_accum = np.zeros((h, w), dtype=np.float64)
        n = 0

        for p in tqdm(paths, desc=f"  Depth [{face:>5s}]", unit="img"):
            img = cv2.imread(str(p))
            if img is None:
                continue
            depth_accum += predict_depth(img, depth_processor, depth_model, device)
            n += 1

        mean_depth = depth_accum / max(n, 1)

        # Normalise to 0-255 for Otsu
        d_min, d_max = mean_depth.min(), mean_depth.max()
        d_norm = ((mean_depth - d_min) / (d_max - d_min + 1e-8) * 255).astype(np.uint8)
        _depth_norm_cache[face] = d_norm  # cache for boundary correction
        otsu_val, _ = cv2.threshold(d_norm, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

        # Use a scaled-down threshold to capture the transition zone
        effective_thresh = int(otsu_val * depth_scale)
        roof_mask = d_norm > effective_thresh
        roof_mask = _keep_bottom_connected(roof_mask)

        # Dilate to catch boundary pixels
        if dilate_px > 0:
            kernel = cv2.getStructuringElement(
                cv2.MORPH_ELLIPSE, (dilate_px, dilate_px),
            )
            roof_mask = cv2.dilate(
                roof_mask.astype(np.uint8), kernel, iterations=1,
            ).astype(bool)

        n_pixels = roof_mask.sum()
        pct = 100 * n_pixels / roof_mask.size
        print(f"  [{face:>5s}] depth roof (Otsu={otsu_val}, eff={effective_thresh}): "
              f"{n_pixels} pixels ({pct:.1f}%)")
        roof_masks[face] = roof_mask

    return roof_masks


# ── Method 2: SegFormer consensus ─────────────────────────────────────

def build_segformer_roof_masks(
    face_groups: dict[str, list[Path]],
    seg_processor: SegformerImageProcessor,
    seg_model: SegformerForSemanticSegmentation,
    device: torch.device,
    consensus_thresh: float = 0.3,
) -> dict[str, np.ndarray]:
    roof_masks: dict[str, np.ndarray] = {}

    for face, paths in face_groups.items():
        sample = cv2.imread(str(paths[0]))
        h, w = sample.shape[:2]
        car_votes = np.zeros((h, w), dtype=np.float32)
        n = len(paths)

        for p in tqdm(paths, desc=f"  SegFormer [{face:>5s}]", unit="img"):
            img = cv2.imread(str(p))
            if img is None:
                continue
            seg = predict_segmentation(img, seg_processor, seg_model, device)
            car_votes += (seg == ADE20K_CAR).astype(np.float32)

        frequency = car_votes / max(n, 1)
        roof_mask = frequency >= consensus_thresh
        roof_mask = _keep_bottom_connected(roof_mask)

        n_pixels = roof_mask.sum()
        pct = 100 * n_pixels / roof_mask.size
        print(f"  [{face:>5s}] SegFormer roof: {n_pixels} pixels ({pct:.1f}%)")
        roof_masks[face] = roof_mask

    return roof_masks


# ── Method 3: Temporal variance ───────────────────────────────────────

def build_temporal_variance_roof_masks(
    face_groups: dict[str, list[Path]],
    std_thresh: float = 12.0,
    dilate_px: int = 15,
) -> dict[str, np.ndarray]:
    roof_masks: dict[str, np.ndarray] = {}

    for face, paths in face_groups.items():
        print(f"  [{face:>5s}] loading {len(paths)} frames …", end="", flush=True)
        imgs = []
        for p in paths:
            img = cv2.imread(str(p))
            if img is not None:
                imgs.append(img.astype(np.float32))

        stack = np.stack(imgs, axis=0)
        std_map = stack.std(axis=0).mean(axis=-1)
        h, w = std_map.shape

        low_var = std_map < std_thresh
        low_var[: h // 3, :] = False
        roof_mask = _keep_bottom_connected(low_var)

        if dilate_px > 0:
            kernel = cv2.getStructuringElement(
                cv2.MORPH_ELLIPSE, (dilate_px, dilate_px),
            )
            roof_mask = cv2.dilate(
                roof_mask.astype(np.uint8), kernel, iterations=1,
            ).astype(bool)

        n_pixels = roof_mask.sum()
        pct = 100 * n_pixels / roof_mask.size
        print(f" temporal roof: {n_pixels} pixels ({pct:.1f}%)")
        roof_masks[face] = roof_mask

    return roof_masks


# ── Visualisation ─────────────────────────────────────────────────────

def visualize_mask(image_bgr: np.ndarray, mask: np.ndarray) -> np.ndarray:
    vis = image_bgr.copy()
    invalid = mask == 0
    vis[invalid] = (vis[invalid] * 0.4 + np.array([0, 0, 200]) * 0.6).astype(np.uint8)
    return vis


# ── Main ──────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Mask sky and car-roof regions")
    parser.add_argument("--images_dir", type=str, default="output/images")
    parser.add_argument("--output_dir", type=str, default="output/masks")
    parser.add_argument("--consensus_thresh", type=float, default=0.3,
                        help="SegFormer car-vote threshold (default: 0.3)")
    parser.add_argument("--std_thresh", type=float, default=12.0,
                        help="Temporal std threshold for static roof (default: 12.0)")
    parser.add_argument("--depth_scale", type=float, default=0.7,
                        help="Scale factor for Otsu depth threshold (default: 0.7)")
    parser.add_argument("--visualize", action="store_true",
                        help="Save overlay visualisations to <output_dir>/vis/")
    parser.add_argument("--device", type=str, default=None)
    args = parser.parse_args()

    images_dir = Path(args.images_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.visualize:
        vis_dir = output_dir / "vis"
        vis_dir.mkdir(parents=True, exist_ok=True)

    if args.device:
        device = torch.device(args.device)
    else:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"[mask] Using device: {device}")

    # Load models
    print("[mask] Loading SegFormer-B5 (ADE20K) …")
    seg_processor, seg_model = load_segformer(device)
    print("[mask] Loading Depth Anything V2 Large …")
    depth_processor, depth_model = load_depth_model(device)

    image_paths = sorted(images_dir.glob("*.png"))
    if not image_paths:
        print(f"[mask] No PNG images found in {images_dir}")
        return

    face_groups = group_by_face(image_paths)

    # ── Pass 1a: Depth Anything V2 consensus roof masks ──────────────
    print(f"[mask] Pass 1a: Depth Anything V2 consensus roof")
    depth_roof = build_depth_roof_masks(
        face_groups, depth_processor, depth_model, device,
        depth_scale=args.depth_scale,
    )

    # ── Pass 1b: SegFormer consensus roof masks ──────────────────────
    print(f"[mask] Pass 1b: SegFormer consensus roof")
    seg_roof = build_segformer_roof_masks(
        face_groups, seg_processor, seg_model, device,
        consensus_thresh=args.consensus_thresh,
    )

    # ── Pass 1c: Temporal variance roof masks ────────────────────────
    print(f"[mask] Pass 1c: temporal variance roof")
    temp_roof = build_temporal_variance_roof_masks(
        face_groups, std_thresh=args.std_thresh,
    )

    # ── Combine all three methods (union) ─────────────────────────────
    # For the right face the roof shifts across frames, so a single
    # consensus mask is inaccurate.  We skip the right face here and
    # handle it per-frame in Pass 2 using individual depth maps.
    roof_masks: dict[str, np.ndarray] = {}
    for face in face_groups:
        if face == "right":
            continue  # handled per-frame below
        combined = (
            depth_roof.get(face, False)
            | seg_roof.get(face, False)
            | temp_roof.get(face, False)
        )
        n = combined.sum()
        pct = 100 * n / combined.size
        print(f"  [{face:>5s}] combined roof: {n} pixels ({pct:.1f}%)")
        roof_masks[face] = combined

    # ── Pass 2: per-image sky mask + roof mask ───────────────────────
    # For right-face images the roof mask is computed per-frame from the
    # individual depth map (the roof position shifts between frames).
    print(f"[mask] Pass 2: generating final masks for {len(image_paths)} images …")
    right_stats = []
    for img_path in tqdm(image_paths, desc="Masking", unit="img"):
        image_bgr = cv2.imread(str(img_path))
        if image_bgr is None:
            tqdm.write(f"[mask] WARNING: cannot read {img_path}, skipping")
            continue

        seg_map = predict_segmentation(image_bgr, seg_processor, seg_model, device)
        sky_mask = seg_map == ADE20K_SKY

        face = face_name_from_path(img_path)

        if face == "right":
            # Per-frame depth-based roof mask
            depth_map = predict_depth(image_bgr, depth_processor, depth_model, device)
            h, w = depth_map.shape
            d_min, d_max = depth_map.min(), depth_map.max()
            d_norm = ((depth_map - d_min) / (d_max - d_min + 1e-8) * 255).astype(np.uint8)
            otsu_val, _ = cv2.threshold(d_norm, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
            effective_thresh = int(otsu_val * args.depth_scale)
            roof_mask = d_norm > effective_thresh
            roof_mask = _keep_bottom_connected(roof_mask)
            right_stats.append(100 * roof_mask.sum() / roof_mask.size)
        else:
            roof_mask = roof_masks.get(face, np.zeros_like(sky_mask))

        combined = sky_mask | roof_mask
        out = np.where(combined, 0, 255).astype(np.uint8)

        mask_path = output_dir / img_path.name
        cv2.imwrite(str(mask_path), out)

        if args.visualize:
            vis = visualize_mask(image_bgr, out)
            cv2.imwrite(str(vis_dir / img_path.name), vis)

    if right_stats:
        print(f"  [right] per-frame depth roof: "
              f"mean={np.mean(right_stats):.1f}%, "
              f"min={np.min(right_stats):.1f}%, "
              f"max={np.max(right_stats):.1f}%")

    # Free depth model memory
    del depth_model, depth_processor
    torch.cuda.empty_cache()

    print(f"[mask] Masks saved to {output_dir}")
    if args.visualize:
        print(f"[mask] Visualisations saved to {vis_dir}")


if __name__ == "__main__":
    main()
